# Generated by Django 6.0 on 2026-01-01 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False, verbose_name='交通手段ID')),
                ('transport_type', models.IntegerField(choices=[(0, '新幹線'), (1, '飛行機'), (2, '車'), (3, '電車'), (4, 'バス'), (5, 'その他自由記入')], verbose_name='交通手段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '交通手段',
                'verbose_name_plural': '交通手段',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('user_name', models.CharField(max_length=64, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'お気に入りリスト',
                'verbose_name_plural': 'お気に入りリスト',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='項目名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.favorite', verbose_name='お気に入りリストID')),
            ],
            options={
                'verbose_name': 'お気に入りリストの項目',
                'verbose_name_plural': 'お気に入りリストの項目',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.IntegerField(choices=[(0, '旅行情報より作成'), (1, '既存テンプレートを反映')], verbose_name='生成タイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('template_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_templates', to='app.template', verbose_name='テンプレート参照元')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': 'テンプレート',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(max_length=64, verbose_name='共有トークン')),
                ('permission_type', models.IntegerField(choices=[(0, '閲覧のみ'), (1, '編集可能')], default=0, verbose_name='編集権限')),
                ('expiration_type', models.IntegerField(choices=[(0, '1か月間'), (1, '旅行終了日翌日'), (2, 'ユーザー入力')], default=0, verbose_name='有効期限タイプ')),
                ('expiration_date', models.DateField(verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template', verbose_name='テンプレートID')),
            ],
            options={
                'verbose_name': '共有リンク',
                'verbose_name_plural': '共有リンク',
            },
        ),
        migrations.CreateModel(
            name='Travel_info',
            fields=[
                ('travel_info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='旅行情報ID')),
                ('travel_title', models.CharField(max_length=100, verbose_name='旅行タイトル')),
                ('start_date', models.DateTimeField(verbose_name='開始日')),
                ('end_date', models.DateTimeField(verbose_name='終了日')),
                ('stay_type', models.IntegerField(choices=[(0, '日帰り'), (1, '宿泊')], verbose_name='宿泊タイプ')),
                ('location', models.IntegerField(choices=[(0, '国内'), (1, '海外')], verbose_name='場所')),
                ('memo', models.CharField(blank=True, max_length=230, verbose_name='メモ')),
                ('status', models.IntegerField(choices=[(0, '未'), (1, '完'), (2, '済')], default=0, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'verbose_name': '旅行情報',
                'verbose_name_plural': '旅行情報',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travel_info', verbose_name='旅行情報ID'),
        ),
        migrations.CreateModel(
            name='TravelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分類名')),
                ('travel_type', models.IntegerField(choices=[(0, '初期作成'), (1, 'ユーザー追加')], verbose_name='分類タイプ')),
                ('category_color', models.IntegerField(choices=[(0, '#e91e63ff'), (1, '#ffb7b2fe'), (2, '#f57c00ff'), (3, '#388e3cff'), (4, '#0097a7ff'), (5, '#303f9ffe'), (6, '#795548ff'), (7, '#7b1fa2ff')], verbose_name='分類カラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.template', verbose_name='テンプレートID')),
            ],
            options={
                'verbose_name': '旅行の分類',
            },
        ),
        migrations.CreateModel(
            name='TravelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='項目名')),
                ('item_checked', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')], verbose_name='チェック済み項目')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('travel_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travelcategory', verbose_name='旅行の分類ID')),
            ],
            options={
                'verbose_name': '旅行の項目',
            },
        ),
        migrations.CreateModel(
            name='Travelmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transport', verbose_name='交通手段ID')),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travel_info', verbose_name='旅行情報ID')),
            ],
            options={
                'verbose_name': '旅行の交通手段',
                'verbose_name_plural': '旅行の交通手段',
                'unique_together': {('travel_info', 'transport')},
            },
        ),
        migrations.AddField(
            model_name='travel_info',
            name='transport',
            field=models.ManyToManyField(through='app.Travelmode', to='app.transport', verbose_name='交通手段'),
        ),
    ]
