# Generated by Django 6.0 on 2026-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.IntegerField(choices=[(0, '新幹線'), (1, '飛行機'), (2, '車'), (3, '電車'), (4, 'バス'), (5, 'その他')], verbose_name='交通手段'),
        ),
        migrations.AlterField(
            model_name='travel_info',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='travel_info',
            name='end_date',
            field=models.DateField(verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='travel_info',
            name='start_date',
            field=models.DateField(verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='travel_info',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
