# Generated by Django 6.0 on 2026-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transport_transport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelmode',
            name='custom_transport_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='交通手段その他内容'),
        ),
    ]
