# Generated by Django 6.0 on 2026-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_travelmode_custom_transport_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='travel_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
