# Generated by Django 6.0 on 2026-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_travel_info_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transport_type',
            field=models.IntegerField(choices=[(0, '飛行機'), (1, '新幹線'), (2, '車'), (3, 'バス'), (4, '電車'), (5, 'その他')], verbose_name='交通手段'),
        ),
    ]
