# Generated by Django 6.0 on 2026-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transport_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='share_token',
            field=models.CharField(max_length=12, unique=True, verbose_name='共有トークン'),
        ),
    ]
