# Generated by Django 6.0 on 2026-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_link_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_draft',
            field=models.IntegerField(default=1, verbose_name='下書きフラグ（0: 完成 / 1: 下書き）'),
        ),
    ]
