# Generated by Django 6.0 on 2026-02-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_template_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='is_draft',
        ),
    ]
